"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["./src/main.py"]
DATA_FILES = ["../frontend/dist"]
OPTIONS = {
    "iconfile": "./icon.icns",
    "packages": ["flask", "werkzeug", "jinja2"],
    "plist": {
        "CFBundleDocumentTypes": [
            {
                "CFBundleTypeName": "Chaos",
                "CFBundleTypeRole": "Editor",
                "CFBundleTypeIconFile": "./icon.icns",
                "LSTypeIsPackage": True,
                "LSItemContentTypes": [".chaos"],
            }
        ]
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
